# -*- coding: utf-8 -*-
"""Quantium 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ygq8V8Wtxx0J69ZIVXijB07WDcc4UZ7
"""

import pandas as pd
import numpy as np

# Load the datasets
transaction_data = pd.read_excel('/content/QVI_transaction_data.xlsx')
purchase_behaviour = pd.read_csv('/content/QVI_purchase_behaviour.csv')

print("Transaction Data Head:")
transaction_data.head()
print("\nPurchase Behaviour Head:")
purchase_behaviour.head()

transaction_data.head()

transaction_data.info()

purchase_behaviour.info()

transaction_data_df = transaction_data.to_csv('transaction_data.csv')

transaction_data = pd.read_csv('/content/transaction_data.csv')

transaction_data.head()

transaction_data.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
for i in transaction_data.columns:
  sns.boxplot(transaction_data[i])
  plt.show()

for i in transaction_data.select_dtypes(include=np.number).columns:
  q3 = transaction_data[i].quantile(0.75)
  q1 = transaction_data[i].quantile(0.25)
  iqr = q3 - q1
  upper_bound = q3 + 1.5 * iqr
  lower_bound = q1 - 1.5 * iqr

  # Cap values above the upper bound with the upper bound
  #transaction_data[col] = np.where(transaction_data[col] > upper_bound, upper_bound, transaction_data[col])
  # Cap values below the lower bound with the lower bound
  #transaction_data[col] = np.where(transaction_data[col] < lower_bound, lower_bound, transaction_data[col])

  # Cap the values in the current column 'i'
  transaction_data[i] = transaction_data[i].clip(lower=lower_bound, upper=upper_bound)

transaction_data.info()

transaction_data['DATE'] = pd.to_datetime(transaction_data['DATE'])

for i in transaction_data.columns:
  sns.boxplot(transaction_data[i])
  plt.show()

# Extract pack size by finding the number before 'g'
transaction_data['PACK_SIZE'] = transaction_data['PROD_NAME'].str.extract('(\d+)(?:g|G)')
transaction_data['PACK_SIZE'] = pd.to_numeric(transaction_data['PACK_SIZE'])

# Check unique pack sizes
print("\nUnique Pack Sizes:")
transaction_data['PACK_SIZE'].unique()

transaction_data.head()

transaction_data['CMPY_NAME'] = transaction_data['PROD_NAME'].str.replace(r'\s*\d+[gG]\s*', '', regex=True).str.strip()

# Extract brand name (first word of PROD_NAME)
transaction_data['BRAND_NAME'] = transaction_data['PROD_NAME'].str.split().str[0]

# Standardize common brand names (e.g., 'RRD' is likely 'Red Rock Deli')
def clean_brand_name(brand):
    if brand in ['RRD', 'Red']: return 'Red Rock Deli'
    if brand in ['Doritos', 'Dorito']: return 'Doritos'
    if brand in ['Kettle', 'KT']: return 'Kettle'
    if brand in ['Infuzions', 'Infzns']: return 'Infuzions'
    if brand in ['Snbts']: return 'Sunbites'
    if brand in ['Tostitos']: return 'Tostitos'
    if brand in ['Woolworths']: return 'Woolworths'
    return brand

transaction_data['BRAND_NAME'] = transaction_data['BRAND_NAME'].apply(clean_brand_name)

print("\nTop 10 Brand Names (after cleaning):")
transaction_data['BRAND_NAME'].value_counts().head(10)

# Merge the two DataFrames
merged_data = pd.merge(transaction_data, purchase_behaviour, on='LYLTY_CARD_NBR', how='left')

print("\nMerged Data Info:")
merged_data.info()

merged_data.head()

merged_data['AVG_PRICE_PER_UNIT'] =  merged_data['TOT_SALES'] / merged_data['PROD_QTY']

merged_data.info()

group_cols = ['LIFESTAGE', 'PREMIUM_CUSTOMER']

# Aggregate metrics by customer segment
customer_metrics = merged_data.groupby(group_cols).agg(
    Total_Sales=('TOT_SALES', 'sum'),
    Total_Transactions=('TXN_ID', 'count'),
    Number_of_Customers=('LYLTY_CARD_NBR', 'nunique'),
    Avg_Price_per_Unit=('AVG_PRICE_PER_UNIT', 'mean')
).reset_index()

customer_metrics

# Calculate derived metrics
customer_metrics['Purchase_Frequency'] = customer_metrics['Total_Transactions'] / customer_metrics['Number_of_Customers']
customer_metrics['Avg_Spend_Per_Customer'] = customer_metrics['Total_Sales'] / customer_metrics['Number_of_Customers']

# Prepare final metrics table and save to CSV
final_metrics = customer_metrics[[
    'LIFESTAGE',
    'PREMIUM_CUSTOMER',
    'Number_of_Customers',
    'Total_Sales',
    'Avg_Spend_Per_Customer',
    'Purchase_Frequency',
    'Avg_Price_per_Unit'
]].sort_values(by='Total_Sales', ascending=False)

final_metrics

# Format for cleaner output
final_metrics_formatted = final_metrics.round({
    'Total_Sales': 2,
    'Avg_Spend_Per_Customer': 2,
    'Purchase_Frequency': 2,
    'Avg_Price_per_Unit': 2
})

# Save the final metrics table
final_metrics_formatted.to_csv('customer_segment_metrics.csv', index=False)
print("Metrics table saved as customer_segment_metrics.csv")

# Create a combined segment label for plotting
metrics_df = final_metrics_formatted.copy()
metrics_df['Segment'] = metrics_df['LIFESTAGE'] + ' - ' + metrics_df['PREMIUM_CUSTOMER']
metrics_df_sorted = metrics_df.sort_values(by='Total_Sales', ascending=False)

# Visualization 1: Total Sales by Segment
plt.figure(figsize=(14, 8))
sns.barplot(x='Total_Sales', y='Segment', data=metrics_df_sorted, palette='viridis')
plt.title('Total Chip Sales by Customer Segment (Overall Value)', fontsize=16)
plt.xlabel('Total Sales ($)', fontsize=12)
plt.ylabel('Customer Segment', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
plt.savefig('total_sales_by_segment.png')
plt.close()

print("Visualization 1 saved as total_sales_by_segment.png")











# Visualization 2: Avg Spend per Customer vs. Avg Price per Unit
plt.figure(figsize=(12, 10))
scatterplot = sns.scatterplot(
    x='Avg_Spend_Per_Customer',
    y='Avg_Price_per_Unit',
    hue='LIFESTAGE',
    size='Number_of_Customers',
    data=metrics_df,
    sizes=(50, 800),
    palette='Set1',
    alpha=0.7
)

# Label the points for key insights (top revenue drivers)
for line in range(0, metrics_df.shape[0]):
     if metrics_df.iloc[line]['Total_Sales'] >= metrics_df_sorted['Total_Sales'].iloc[1] or \
        metrics_df.iloc[line]['Avg_Price_per_Unit'] > 3.75:
        plt.text(
            metrics_df.iloc[line]['Avg_Spend_Per_Customer'] + 0.5,
            metrics_df.iloc[line]['Avg_Price_per_Unit'],
            metrics_df.iloc[line]['Segment'].replace(' - ', '\n'),
            horizontalalignment='left',
            size='small',
            color='black',
            weight='semibold'
        )

plt.title('Segment Purchasing Behavior: Avg Spend vs. Avg Price (Bubble Size = Customer Count)', fontsize=16)
plt.xlabel('Average Spend Per Customer ($)', fontsize=12)
plt.ylabel('Average Price Per Unit ($)', fontsize=12)
plt.legend(title='Lifestage', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout(rect=[0, 0, 0.9, 1])
plt.show()
plt.savefig('avg_spend_vs_avg_price.png')
plt.close()
print("Visualization 2 saved as avg_spend_vs_avg_price.png")

print("\nAnalysis complete. Check your directory for the generated CSV and PNG files.")



"""# Insight

The customer segmentation analysis reveals several key insights into purchasing behaviors across different lifestage and premium customer groups:

**Top Performing Segments (by Total Sales):**
The highest revenue-generating segments are:
*   **Older Families - Budget**: This group leads in total sales ($167,991.15), demonstrating strong purchasing power and frequency.
*   **Young Singles/Couples - Mainstream**: A significant contributor to overall sales ($157,410.20), indicating a large customer base with regular purchases.
*   **Retirees - Mainstream**: Another high-volume segment ($155,510.35), highlighting the importance of retired customers to the business.

**High-Value Customer Behavior:**
*   **Older Families (Mainstream and Budget)** consistently show both high average spend per customer ($36.48 and $35.96 respectively) and high purchase frequency (5.03 and 4.96 respectively). These customers are highly engaged and loyal, making them critical for sustained revenue.
*   **Young Families (Budget and Premium)** also exhibit strong average spend ($34.65 and $34.50 respectively) and purchase frequency (4.76 and 4.75 respectively), suggesting they are valuable segments to nurture.

**Price Sensitivity and Premium Preferences:**
*   **Midage Singles/Couples - Mainstream** and **Young Singles/Couples - Mainstream** show a higher average price per unit ($3.82 and $3.77 respectively), indicating a preference for more premium or larger-pack products within their respective categories. This contrasts with "Young Singles/Couples - Budget" and "Premium" who have the lowest average prices per unit ($3.31 and $3.31 respectively). This suggests that the 'Mainstream' segment within Young Singles/Couples might be more willing to spend on higher-value chip products.
*   While "Young Singles/Couples - Mainstream" has high total sales and a good average price per unit, "Young Singles/Couples - Budget" and "Premium" have significantly lower average prices, indicating a possible opportunity to upsell or understand differing product preferences within this lifestage.

**Underperforming Segments & Opportunities:**
*   **New Families** across all premium customer types (Budget, Mainstream, Premium) represent the lowest-performing segments in terms of total sales, average spend per customer, and purchase frequency. This group could be a focus for targeted marketing campaigns to increase engagement and basket size, possibly with family-sized products or introductory offers.

**Strategic Recommendations:**
*   **Focus on Retention and Loyalty Programs** for "Older Families" and "Retirees" to maintain their high engagement and spend.
*   **Investigate and Promote Higher-Value Products** to "Mainstream Midage Singles/Couples" and "Mainstream Young Singles/Couples" to capitalize on their willingness to purchase higher-priced items.
*   **Develop Tailored Campaigns** for "New Families" to address their lower engagement and encourage increased purchasing. This could involve understanding their specific needs and offering relevant promotions or product bundles.
"""

final_metrics_formatted

"""## Customer Segmentation Analysis: Key Insights

The customer segmentation analysis reveals several key insights into purchasing behaviors across different lifestage and premium customer groups:

### Top Performing Segments (by Total Sales):
The highest revenue-generating segments are:
*   **Older Families - Budget**: This group leads in total sales ($167,991.15), demonstrating strong purchasing power and frequency.
*   **Young Singles/Couples - Mainstream**: A significant contributor to overall sales ($157,410.20), indicating a large customer base with regular purchases.
*   **Retirees - Mainstream**: Another high-volume segment ($155,510.35), highlighting the importance of retired customers to the business.

### High-Value Customer Behavior:
*   **Older Families (Mainstream and Budget)** consistently show both high average spend per customer ($36.48 and $35.96 respectively) and high purchase frequency (5.03 and 4.96 respectively). These customers are highly engaged and loyal, making them critical for sustained revenue.
*   **Young Families (Budget and Premium)** also exhibit strong average spend ($34.65 and $34.50 respectively) and purchase frequency (4.76 and 4.75 respectively), suggesting they are valuable segments to nurture.

### Price Sensitivity and Premium Preferences:
*   **Midage Singles/Couples - Mainstream** and **Young Singles/Couples - Mainstream** show a higher average price per unit ($3.82 and $3.77 respectively), indicating a preference for more premium or larger-pack products within their respective categories. This contrasts with "Young Singles/Couples - Budget" and "Premium" who have the lowest average prices per unit ($3.31 and $3.31 respectively). This suggests that the 'Mainstream' segment within Young Singles/Couples might be more willing to spend on higher-value chip products.
*   While "Young Singles/Couples - Mainstream" has high total sales and a good average price per unit, "Young Singles/Couples - Budget" and "Premium" have significantly lower average prices, indicating a possible opportunity to upsell or understand differing product preferences within this lifestage.

### Underperforming Segments & Opportunities:
*   **New Families** across all premium customer types (Budget, Mainstream, Premium) represent the lowest-performing segments in terms of total sales, average spend per customer, and purchase frequency. This group could be a focus for targeted marketing campaigns to increase engagement and basket size, possibly with family-sized products or introductory offers.

### Strategic Recommendations:
*   **Focus on Retention and Loyalty Programs** for "Older Families" and "Retirees" to maintain their high engagement and spend.
*   **Investigate and Promote Higher-Value Products** to "Mainstream Midage Singles/Couples" and "Mainstream Young Singles/Couples" to capitalize on their willingness to purchase higher-priced items.
*   **Develop Tailored Campaigns** for "New Families" to address their lower engagement and encourage increased purchasing. This could involve understanding their specific needs and offering relevant promotions or product bundles.

## Summary:

### Data Analysis Key Findings
*   **Top-Performing Segments by Total Sales:**
    *   "Older Families - Budget" leads with \$167,991.15 in total sales, an average spend of \$35.96 per customer, and a purchase frequency of 4.96.
    *   "Young Singles/Couples - Mainstream" is a significant contributor with \$157,410.20 in total sales.
    *   "Retirees - Mainstream" follows with \$155,510.35 in total sales.
*   **High-Value Customer Behavior:**
    *   "Older Families" (Mainstream and Budget) consistently show high average spend per customer (\$36.48 and \$35.96 respectively) and high purchase frequency (5.03 and 4.96 respectively).
    *   "Young Families" (Budget and Premium) also exhibit strong average spend (\$34.65 and \$34.50 respectively) and purchase frequency (4.76 and 4.75 respectively).
*   **Price Sensitivity and Premium Preferences:**
    *   "Midage Singles/Couples - Mainstream" and "Young Singles/Couples - Mainstream" show a higher average price per unit (\$3.82 and \$3.77 respectively), indicating a preference for more premium products.
    *   In contrast, "Young Singles/Couples - Budget" and "Premium" have the lowest average prices per unit (\$3.31 each), suggesting price sensitivity.
*   **Underperforming Segments:**
    *   "New Families" across all premium types (Budget, Mainstream, Premium) represent the lowest-performing segments in terms of total sales (\$21,906.95, \$16,999.95, \$11,480.30 respectively), average spend, and purchase frequency.

### Insights or Next Steps
*   **Strategic Recommendations:** Focus on retention and loyalty programs for "Older Families" and "Retirees" due to their high engagement and spend.
*   **Product Promotion:** Investigate and promote higher-value products to "Mainstream Midage Singles/Couples" and "Mainstream Young Singles/Couples" to capitalize on their willingness to purchase higher-priced items.
*   **Targeted Campaigns:** Develop tailored marketing campaigns for "New Families" to address their lower engagement and encourage increased purchasing, potentially with family-sized products or introductory offers.
"""